### ISSUE TITLE
using rnn-t on  librispeech recipe

### ISSUE THREAD

**Issue by WanderingSven** [espnet/espnet#1888]
hi,everyone
      I try to use rnn-t configure from /egs/vivos/asr1/conf/tuning/transfucer/train_transformer-rnn_transducer.yaml on librispeech recipe. However, it has an error after one epcho.What is the possible cause of the problem?
![图片](https://user-images.githubusercontent.com/26950286/80555602-54c5b700-8a03-11ea-84c7-ac63949ce281.png)

**Comment by b-flo** [comment]
Hi,

As you didn't provide the complete stack trace, I'll assume it's the same issue as #1860, which was fixed some days ago. Could you re-build warp-transducer and try again?

```
cd espnet/tools
rm -rf warp-transducer warp-transducer.done
make warp-transducer.done
```

**Comment by WanderingSven** [comment]
thank you for your help@b-flo  I will try it.

**Comment by housebaby** [comment]
> thank you for your help@b-flo I will try it.

@WanderingSven Did it work out ? Is the "illegal memory access" problem fixed?

**Comment by housebaby** [comment]
> > thank you for your help@b-flo I will try it.
> 
> @WanderingSven Did it work out ? Is the "illegal memory access" problem fixed?

I think my warp-transducer is up-to-date, but the same problem still exists

**Comment by WanderingSven** [comment]
it works now @housebaby

**Comment by housebaby** [comment]
> it works now @housebaby
How to make it work. Update warp_transducer or update espnet. I am using espnet1
